version: '3'
services:
  
  demo:
    build: .
    ports:
      - "5000:5000"
    # links:
    #   - redis:redis
    volumes:
      - .:/demo
    # depends_on:
    #   - redis
  # redis:
  #   image: "redis:alpine"
  #   volumes:
  #     - E:\data\redis:/var/lib/redis
  #   ports:
  #     - "6379:6379"